#!/usr/bin/env python3

import argparse
import json
import os

import evalrescallers_paper


parser = argparse.ArgumentParser(
    description = 'Makes figures and tables for paper',
    usage='%(prog)s <summary.json> <out_directory>',
)
parser.add_argument('summary_json', help='Summary json file made by tb-amr-benchmarking pipeline')
parser.add_argument('outdir', help='Directory name for output files (must not already exist)')
parser.add_argument('--debug', action='store_true', help='Do not delete temp files')
options = parser.parse_args()

options.summary_json = os.path.abspath(options.summary_json)

try:
    os.mkdir(options.outdir)
except:
    raise Exception(f'Error making output directory "{options.outdir}". Cannot continue')

os.chdir(options.outdir)

with open(options.summary_json) as f:
    json_data = json.load(f)

r_is_res_prefix = 'r_is_resistant'
summary_data_handler = evalrescallers_paper.summary_data_handler.SummaryDataHandler(
    json_data, 'tb', r_means_resistant=True)
summary_data_handler.run(r_is_res_prefix)

r_is_susc_prefix = 'r_is_susceptible'
summary_data_handler = evalrescallers_paper.summary_data_handler.SummaryDataHandler(
    json_data, 'tb', r_means_resistant=False)
summary_data_handler.run(r_is_susc_prefix)


map_files_prefix = 'figure.map'
run_time_and_memory_tsv = 'supplementary.table.run_time_and_memory.tsv'
run_time_and_memory_plot_prefix = 'supplementary.figure.resources'


evalrescallers_paper.maps.make_maps(map_files_prefix, debug=options.debug)
with open(options.summary_json) as f:
    json_data = json.load(f)
evalrescallers_paper.run_time_and_memory.json_to_tsv(json_data, run_time_and_memory_tsv)
evalrescallers_paper.run_time_and_memory.tsv_to_plot(run_time_and_memory_tsv, run_time_and_memory_plot_prefix)

